// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcddaturl4Dx0RD4McRTCJ-UTKFgckRG4',
    appId: '1:764024714663:web:a233e6030c13bdc84a3282',
    messagingSenderId: '764024714663',
    projectId: 'book-store-5b166',
    authDomain: 'book-store-5b166.firebaseapp.com',
    storageBucket: 'book-store-5b166.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgO3T91_6KDmsmzTjgGO-aTtTb6bwv1nw',
    appId: '1:764024714663:android:4f36576f6fa909a74a3282',
    messagingSenderId: '764024714663',
    projectId: 'book-store-5b166',
    storageBucket: 'book-store-5b166.appspot.com',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyDnamlN1r3Fdq4H0_a_YRI4pPAUWZBQoCE',
  //   appId: '1:764024714663:web:a233e6030c13bdc84a3282',
  //   messagingSenderId: '764024714663',
  //   projectId: 'book-store-5b166',
  //   storageBucket: 'cp-book-store.appspot.com',
  //   iosBundleId: 'com.example.cpBookStore',
  // );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyDnamlN1r3Fdq4H0_a_YRI4pPAUWZBQoCE',
  //   appId: '1:75090155947:ios:d5d2d93ced71fd9e14daee',
  //   messagingSenderId: '75090155947',
  //   projectId: 'cp-book-store',
  //   storageBucket: 'cp-book-store.appspot.com',
  //   iosBundleId: 'com.example.cpBookStore.RunnerTests',
  // );
}
